name: 'ATS'
description: 'RUN ATS'
inputs:
  container:
    description: 'container to run in'
    required: false
outputs:
  random-number:
    description: "Random number"
    value: 1
runs:
  using: "composite"
  steps:
    - run: echo command="docker exec ${{ inputs.container }}" >> $GITHUB_OUTPUT
      id: command
      shell: bash
    - id: container-running
      run: docker ps | grep ${{ inputs.container }}
      shell: bash
    - run: ${{ steps.random-number-generator.outputs.random-number }} ls
      shell: bash
